from typing import Self  # noqa: I001

from jax.typing import ArrayLike


class ArrayTreeOps:
    # Unary
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __abs__(self) -> Self: ...

    # Binary
    def __add__(self, other: Self | ArrayLike) -> Self: ...
    def __sub__(self, other: Self | ArrayLike) -> Self: ...
    def __mul__(self, other: Self | ArrayLike) -> Self: ...
    def __truediv__(self, other: Self | ArrayLike) -> Self: ...
    def __floordiv__(self, other: Self | ArrayLike) -> Self: ...
    def __mod__(self, other: Self | ArrayLike) -> Self: ...
    def __pow__(self, other: Self | ArrayLike) -> Self: ...

    def __radd__(self, other: Self | ArrayLike) -> Self: ...
    def __rsub__(self, other: Self | ArrayLike) -> Self: ...
    def __rmul__(self, other: Self | ArrayLike) -> Self: ...
    def __rtruediv__(self, other: Self | ArrayLike) -> Self: ...
    def __rfloordiv__(self, other: Self | ArrayLike) -> Self: ...
    def __rmod__(self, other: Self | ArrayLike) -> Self: ...
    def __rpow__(self, other: Self | ArrayLike) -> Self: ...

    # Ordering
    def __lt__(self, other: Self | ArrayLike) -> Self: ...
    def __le__(self, other: Self | ArrayLike) -> Self: ...
    def __gt__(self, other: Self | ArrayLike) -> Self: ...
    def __ge__(self, other: Self | ArrayLike) -> Self: ...
